---
env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - sort-exports
  - prefer-arrow
  - typescript-sort-keys
  - sort-keys-fix
rules:
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: comma
        requireLast: false
      overrides:
        interface:
          multiline:
            delimiter: semi
            requireLast: true
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/sort-type-union-intersection-members": error
  "@typescript-eslint/no-unused-vars":
    - warn
    - ignoreRestSiblings: true
  "@typescript-eslint/ban-ts-comment":
    - error
    - ts-expect-error:
        descriptionFormat: '^: TS\d+ because .+$'
  arrow-body-style:
    - error
    - as-needed
  spaced-comment: error
  object-shorthand: error
  brace-style:
    - error
    - 1tbs
  comma-dangle:
    - error
    - never
  curly: error
  func-style:
    - error
    - expression
  import/order:
    - error
    - alphabetize:
        order: asc
      groups:
        - builtin
        - external
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: never
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-multi-spaces: error
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  prefer-arrow/prefer-arrow-functions:
    - error
    - singleReturnOnly: true
  prefer-template: error
  quotes:
    - error
    - single
  semi: "off"
  sort-exports/sort-exports:
    - error
    - sortDir: asc
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  sort-keys-fix/sort-keys-fix:
    - error
    - asc
    - caseSensitive: true
      natural: true
  typescript-sort-keys/interface:
    - error
    - asc
    - caseSensitive: true
      natural: true
      requiredFirst: true
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
